### ISSUE TITLE
Multiple artist value.

### ISSUE THREAD

**Issue by PhyX-Meow** [pnck/foo_input_ncm#6] opened 2024-04-23 01:08 UTC
The same artist is shown twice. See picture:
![image](https://github.com/pnck/foo_input_ncm/assets/17513581/2a291da4-e2b9-4d31-9622-8865b445df74)
Example file: https://1drv.ms/u/s!AnsQDRnK8xdghdwV7ksMemOC0SRxCQ?e=mtO4o9

Foobar2000: v2.1.2 [x64] on Win11
foo_input_ncm: v0.3.4

**Comment by pnck** [comment] 2024-04-25 09:23
@PhyX-Meow 

This is caused by the original meta info tags within the wrapped audio content.

The `<artists>` field is composed of both the wrapped audio and the `NCM` meta info JSON, and if the wrapped audio contains another (identical) tag, it will be "shown twice".

This is easy to fix, but I'm planning to add a conversion menu to let users extract the original audio file, which is much faster than converting with codecs. (The Mac version doesn't even have a convert functionality yet.)

So please wait a while.

**Comment by pnck** [comment] 2024-04-27 11:46
should have been fixed in [the v0.4.1 release ](https://github.com/pnck/foo_input_ncm/releases/tag/v0.4.1)

**Closed by pnck** 2024-04-27 11:46 UTC
Labels: good first issue
